type: google.api.Service
config_version: 3

http:
  rules:
    - selector: fauxstodian.v1.FauxstodianService.CreateAccount
      post: /fauxstodian/api/v1/account
      body: "*"
    - selector: fauxstodian.v1.FauxstodianService.GetBalance
      post: /fauxstodian/api/v1/balance
      body: "*"
    - selector: fauxstodian.v1.FauxstodianService.TransferOwnership
      post: /fauxstodian/api/v1/transfer
      body: "*"
    - selector: fauxstodian.v1.FauxstodianService.CloseAccount
      post: /fauxstodian/api/v1/close
      body: "*"
